export {default as NavBar} from './NavBar/NavBar'
export {default as Header} from './Header/Header'
export {default as Hero} from './Hero/Hero'
export {default as MostPoupular} from './MostPoupular/MostPoupular'
export {default as Footer } from './Footer/Footer'
